create database customer_behaviour;
use customer_behaviour;

show tables;
select * from customer;

#Q1. What is the total revenue generated by male vs. female customers?
select gender, sum(purchase_amount) as revenue from customer group by gender;

#Q2. Which customers used a discount but still spent more than the average purchase amount?
select customer_id, purchase_amount from customer 
where discount_applied="yes" and purchase_amount>= (select avg(purchase_amount) from customer);

#Q3. Which are the top 5 products with the highest average review rating?
SELECT item_purchased,
       ROUND(AVG(review_rating), 2) AS avg_rating
FROM customer
GROUP BY item_purchased
ORDER BY avg_rating DESC
LIMIT 5;

#Q4. Compare the average purchase amounts between Standard and Express shipping.
select shipping_type, round(avg(purchase_amount),2) as avg_purchase_amount from customer
 where shipping_type in ("standard","express") group by shipping_type;

#Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
select subscription_status,count(customer_id) as total_customers,
 round(avg(purchase_amount),2) as avg_spend, round(sum(purchase_amount),2) as total_revenue
 from customer group by subscription_status;


#Q6. Which 5 products have the highest percentage of purchases with discounts applied?
#select item_purchased,sum(purchase_amount) as total_sales from customer where discount_applied="yes"
# group by item_purchased order by total_sales desc limit 5; 
 
 select item_purchased,round(100 * sum(case when discount_applied="yes" then 1 else 0 end)/count(*),2) as discount_purchase_rate from customer
 group by item_purchased order by discount_purchase_rate desc limit 5; # these product rely heavely on discounts to sale 
 
#Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
with customer_type as( 
select customer_id,previous_purchases,
case 
	when previous_purchases=1 then "New"
    when previous_purchases between 2 and 10 then "returning"
    else "loyal"
    end as customer_segment
from customer
)
select customer_segment,count(*) as "Number of customers"
from customer_type
group by customer_segment ;

#Q8. What are the top 3 most purchased products within each category?
with item_count as(
select category,item_purchased, count(item_purchased) as total_orders,
row_number() over(partition by category order by count(item_purchased) desc) as item_rank
from customer group by category,item_purchased
)
select item_rank,category ,item_purchased ,total_orders from item_count where item_rank<=3;

#Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status , count(customer_id) as repeat_buyers from customer where previous_purchases>5
group by subscription_status;

#Q10. What is the revenue contribution of each age group?
select age_group,sum(purchase_amount) as total_revenue from customer 
group by age_group order by total_revenue desc;
